// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7EwLTP_-SDys7xgw4kQl7SgxrUz9d2RI',
    appId: '1:559569250822:android:0e9e8580ba22c649b8b187',
    messagingSenderId: '559569250822',
    projectId: 'flutter-chat-app-e5fb6',
    storageBucket: 'flutter-chat-app-e5fb6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApGlIlY2_tlzR3QGPBG-pvFQ_WVmsDY1o',
    appId: '1:559569250822:ios:b2d1a77bf28d25f0b8b187',
    messagingSenderId: '559569250822',
    projectId: 'flutter-chat-app-e5fb6',
    storageBucket: 'flutter-chat-app-e5fb6.appspot.com',
    iosClientId: '559569250822-pe8k2g4g60jg8ced4bn9tdqpl139ocuv.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterChatApp',
  );
}
